connectedin/connectedin/urls.py
from django.contrib import admin
from django.urls import path
from perfis import views 
from usuarios.views import RegistarUsuarioView
from django.contrib.auth import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name='index'),
    path('perfil/<int:perfil_id>', views.exibir_perfil, name='exibir'),
    path('perfil/<int:perfil_id>/convidar',views.convidar, name='convidar'),
    path('convite/<int:convite_id>/aceitar',views.aceitar, name='aceitar'),
    path('convite/<int:convite_id>/recusar',views.recusar, name='recusar'),
    path('convite/<int:perfil_id>/desfazer',views.desfazer_amizade, name='desfazer'),
    path('registrar/',RegistarUsuarioView.as_view(),name='registrar'),
    path('perfil/mudar_senha',views.mudar_senha,name='mudar_senha'),
    path('perfil/alterar_senha',views.alterar_senha,name='alterar_senha'),
    path('login/', v.LoginView.as_view(template_name='login.html'), name = 'login'), 
    path('logout/', v.LogoutView.as_view(template_name='login.html'), name="logout"),
    path('perfil/pesquisar',views.pesquisar,name='pesquisar'),
    path('perfil/mostrar',views.realizar_pesquisa,name='realizar_pesquisa'),
    path('perfil/timeline',views.exibir_timeline,name='timeline'),
    path('perfil/post',views.incluir_post,name='incluir_post'),
    path('perfil/<int:id_post>/excluir',views.excluir_post,name='excluir_post'),
]

connectedin/perfis/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Perfil(models.Model):
    nome = models.CharField(max_length=255, null=False)
    telefone = models.CharField(max_length=20, null= False)
    nome_empresa = models.CharField(max_length=255, null=False)
    contatos = models.ManyToManyField('Perfil')
    usuario = models.OneToOneField(User, related_name="perfil", on_delete = models.CASCADE,default="", editable=False) 

    def __str__(self):
        return self.nome

    @property 
    def email(self): 
        return self.usuario.email

    def convidar(self, perfil_convidado):
        #if self.pode_convidar(perfil_convidado):
        convite = Convite(solicitante=self,convidado = perfil_convidado)
        convite.save()

    def desfazer(self,perfil):
        self.contatos.remove(perfil)
        perfil.contatos.remove(self)

    def remove(self,perfil):
        pass


class Convite(models.Model):
    solicitante = models.ForeignKey(Perfil,on_delete=models.CASCADE,related_name='convites_feitos' )
    convidado = models.ForeignKey(Perfil, on_delete= models.CASCADE, related_name='convites_recebidos')

    def aceitar(self):        
        self.solicitante.contatos.add(self.convidado)
        self.convidado.contatos.add(self.solicitante)
        self.delete()
    
    def recusar(self):
        self.delete()

'''class Timeline(models.Model):
    perfil = models.OneToOneField(Perfil,related_name='timeline',on_delete=models.CASCADE)'''

class Post(models.Model):
    texto = models.CharField(max_length=140)
    data = models.DateTimeField(auto_now=True)
    timeline = models.ForeignKey(Perfil, related_name = 'timeline' ,on_delete = models.CASCADE)

connectedin/usuarios/models.py
from django.db import models

# Create your models here.

connectedin/perfis/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

class PostForm(ModelForm):
    class Meta:
        model=Post
        fields=('texto',)

connectedin/usuarios/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrarUsuarioForm(forms.Form): 
    nome = forms.CharField(required=True) 
    email = forms.EmailField(required=True) 
    senha = forms.CharField(required=True) 
    telefone = forms.CharField(required=True) 
    nome_empresa = forms.CharField(required=True)

    def is_valid(self): 
        valid = True 
        if not super(RegistrarUsuarioForm, self).is_valid(): 
            self.adiciona_erro('Por favor, verifique os dados informados')
            user_exists = User.objects.filter(username=self.cleaned_data['nome']).exists()
            valid = False 
            if user_exists: 
                self.adiciona_erro('Usuário já existente.')  
                valid = False
        return valid
    def adiciona_erro(self, message): 
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList()) 
        errors.append(message)

connectedin/perfis/views.py
from perfis.models import Perfil, Convite,Post
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
# Create your views here.
from django.http import HttpResponseNotFound,HttpResponseRedirect
from .forms import *
from django.contrib.auth import authenticate, login, logout

@login_required
def index(request):
	return render(request, 'index.html',{'perfis' : Perfil.objects.all(),'perfil_logado' : get_perfil_logado(request)})

@login_required
def exibir_perfil(request, perfil_id):

	perfil = Perfil.objects.get(id=perfil_id)

	return render(request, 'perfil.html',
		          {'perfil' : perfil, 
				   'perfil_logado' : get_perfil_logado(request)})

@login_required
def convidar(request,perfil_id):

	perfil_a_convidar = Perfil.objects.get(id=perfil_id)
	perfil_logado = get_perfil_logado(request)
	
	#if(perfil_logado.pode_convidar(perfil_a_convidar)):
	perfil_logado.convidar(perfil_a_convidar)
	
	return  redirect('index')

@login_required
def get_perfil_logado(request):
	#if request.user.is_authenticated: 
	profile=request.user.perfil
	return profile
	#else: 
		#return HttpResponseNotFound('sem perfil')

@login_required
def recusar(request,convite_id):
    convite=Convite.objects.get(id=convite_id)
    convite.recusar()
    return redirect('index')

@login_required
def aceitar(request, convite_id):
	convite = Convite.objects.get(id = convite_id)
	convite.aceitar()
	return redirect('index')

@login_required
def desfazer_amizade(request,perfil_id):
	perfil = Perfil.objects.get(id=perfil_id)
	perfil.desfazer(get_perfil_logado(request))
	return redirect('index')

@login_required
def alterar_senha(request):
	return render(request,'alterar_senha.html')
	'''buscar a senha do usuario, mostrar e mandar ele
	digitar uma nova senha para ser salva'''
@login_required
def mudar_senha(request):
	senha=request.GET['nova_senha']
	perfil=request.user
	perfil.set_password(senha)
	#perfil.usuario.password=senha
	perfil.save()
	perfil_autenticado=authenticate(username=request.user.username,password=senha)
	login(request,perfil_autenticado)
	return redirect('index')

@login_required
def pesquisar(request):
    return render(request,'pesquisa_usuario.html')

@login_required
def realizar_pesquisa(request):
	nome=request.GET['nome']
	perfis = Perfil.objects.filter(nome__contains=nome)
	return render(request,'mostrar_pesquisa.html',{'perfil':perfis})
	pass

@login_required
def exibir_timeline(request):
    posts=request.user.perfil.timeline
    return render(request,'timeline.html',{'posts':posts})

@login_required
def incluir_post(request):
    if request.method == 'POST':
        postform = PostForm(request.POST or None)
        if postform.is_valid():
            postinstance = postform.save(commit=False)
            postinstance.timeline=request.user.perfil
            postinstance.save()
            return redirect('index')
    else:
        postform=PostForm()
    return render(request,'add_post.html',{'post':postform})

@login_required
def excluir_post(request,id_post):
    Post.objects.filter(id=id_post).delete()
    return redirect('timeline')
    
def recuperar_senha(request):
    '''O usuario fornece o email e nome e o sistema busca no banco o seu registro
	para mudança de senha'''

connectedin/usuarios/views.py
from django.shortcuts import render,redirect
from django.views.generic.base import View
from django.contrib.auth.models import User
from perfis.models import Perfil 
from usuarios.forms import RegistrarUsuarioForm

# Create your views here.

class RegistarUsuarioView(View):

    template_name = 'registrar.html'

    def get(self,request):
        return render(request,self.template_name)
    
    def post(self,request):
        form = RegistrarUsuarioForm(request.POST) 
        if form.is_valid(): 
            dados_form = form.cleaned_data 
            usuario = User.objects.create_user(username = dados_form['nome'], 
                                        email = dados_form['email'], 
                                        password = dados_form ['senha'])
            perfil = Perfil(nome=dados_form['nome'], 
                            telefone=dados_form['telefone'], 
                            nome_empresa=dados_form['nome_empresa'],
                             usuario=usuario) 
            perfil.save() 
            return redirect('index')
        return render(request, self.template_name, {'form' : form})

connectedin/perfis/templates/add_post.html
{% extends 'base.html' %}
{% block body %}
<html>
    <head></head>
    <body>
        <h3>Adicionar Post</h3>
        <form method="post">
            {% csrf_token %}
            {{post.as_p}}
            <input type="submit" >
        </form>
    </body>
</html>
{%endblock%}

connectedin/perfis/templates/alterar_senha.html
<div>
<form method="GET" action="{% url 'mudar_senha' %}">
 <h1>Digite a nova senha</h1>
    <input type="search" placeholder="Mudar senha" aria-label="" name="nova_senha">
    <button type="submit">Alterar senha</button> 
</form>
</div>

connectedin/perfis/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang = "pt-br">
	<head>
		<meta charset="utf-8">
		<title>ConnectedIn</title>
		<link rel="stylesheet" 
			 href="{% static 'styles/bootstrap.css' %}">
		<link rel="stylesheet" 
			 href="{% static 'styles/main.css' %}">

	</head>
	<body>
		<div class="container">
			<div class = "header">
				<ul class = "nav nav-pills pull-right">
					<li><a href = "{% url 'index' %}">{{ perfil_logado.nome }}</a></li>
					<li><a href = "/logout/">Logout</a></li>
					<li><a href = "{% url 'pesquisar' %}">Pesquisar Usuario</a></li>
					<li><a href = "{% url 'alterar_senha' %}">Mudar Senha</a></li>
				</ul>
				<h3 class = "text-muted">ConnectedIn</h3>
			</div>
			
			<div class="row content">
				{% block body%}
				{% endblock %}				
			</div>		
		</div>	
	</body>
</html>

connectedin/perfis/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="col-lg-12"> 		
	<div class="panel panel-default">
		<div class="panel-heading">
			<strong>Todos os perfis</strong>
		</div>
		{% if perfis %}
		<ul class="list-group">
			{% for perfil in perfis %}
				<li class="list-group-item">
					<a href = "{% url 'exibir' perfil.id %}">	{{ perfil.nome }} / {{ perfil.email }}
					</a>	
				</li>
			{% endfor %}
		{% else %}	
			<p>Não há perfis cadastrados</p>
		{% endif %}
		</ul>
	</div>	

    <div class="panel panel-default">
        {% with total=perfil_logado.contatos.count %}
            {% if total %}
                <div class="panel-heading">
                    <strong> {{ total }}  
                        Contato{{ total|pluralize }}
                    </strong>
                </div>
                <ul class="list-group">
                    {% for perfil in perfil_logado.contatos.all %}
                        <li class = "list-group-item">
                            <a href = "{% url 'exibir' perfil.id %}">
                                {{ perfil }}
                            </a>
                            <a class="pull-right" href="{% url 'desfazer' perfil.id %}">
                                desfazer amizade
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="panel-body">
                    Não há contatos :(
                </div>    
            {% endif %}
        {% endwith %}    
    </div>    

    <div class="panel panel-default">
        {% with total=perfil_logado.convites_recebidos.count %}

            {% if total %}
                <div class="panel-heading">
                    <strong> {{ total }}  
                    Convite{{ total|pluralize }} aguardando aprovação</strong>
                </div>
                <ul class="list-group">
                    {% for convite in perfil_logado.convites_recebidos.all %}
                        <li class = "list-group-item">
                           <ul class = "list-inline">
                                <li class = "list-inline-item">
                                    <a href = "{% url 'exibir' convite.solicitante.id %}">
                                        {{convite.solicitante.nome}}
                                    </a>
                                </li>
                                <li class = "list-inline-item pull-right">
                                    <a href = "{% url 'recusar' convite.id %}">recusar</a>
                                </li>
                                <li class = "list-inline-item pull-right">
                                    <a href = "{% url 'aceitar' convite.id %}">aceitar</a>
                                </li>
                        
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="panel-body">
                    Não há convites
                </div>    
            {% endif %}
        {% endwith %}    
    </div>
    <div class="panel panel-default">
    <div class="panel-body">
        <a href = "{% url 'timeline'%}">Ver timeline</a>
    </div> 
    </div>
</div>
{% endblock %}

connectedin/perfis/templates/mostrar_pesquisa.html
{% extends 'base.html' %}
{% block body %}
{% if perfil|length > 0 %}
    {% for p in perfil %}
    <h3>Nome do usuario</h3>
        <p>{{p.nome}}</p>
    <h3>Nome da empresa</h3>
        <p>{{p.nome_empresa}}</p>
    {%endfor%}
{% else %}
    <p>sem perfis</p>
{%endif%}
{%endblock%}

connectedin/perfis/templates/perfil.html
{% extends 'base.html' %}
{% block body %}
<div class = "col-lg-12">
		<h2 style="margin-top: 0px">{{ perfil.nome }}</h2>
		<address>			
			<a href = "mailto:{{ perfil.email }}">{{ perfil.email }}</a>
			<br>
			<strong>{{ perfil.nome_empresa }}</strong>
		
		</address>

		<a href = "{% url 'convidar' perfil.id %}">
			Convidar
		</a>
</div>		
{% endblock %}		

connectedin/perfis/templates/pesquisa_usuario.html
{% extends 'base.html' %}
{% block body %}
<div>
<form method="GET" action="{% url 'realizar_pesquisa' %}">
 <h1>Digite o nome a ser procurado</h1>
    <input type="search" placeholder="Procurar Usuario" aria-label="" name="nome">
    <button type="submit">Procurar</button> 
</form>
</div>
{%endblock%}

connectedin/perfis/templates/timeline.html
{% extends 'base.html' %}
{% block body %}
<html>
    <head></head>
    <body>
        <h3>Posts</h3>
            {% for p in posts.all %}
                <div>
                <h2>{{p.texto}}</h2>
                <p>{{p.data}}</p>
                <a href="{% url 'excluir_post' p.id %}">Deletar Post</a>
                </div>
            {% endfor %}
        <a href="{% url 'incluir_post' %}">Adicionar</a>
        <a href="{% url 'index' %}">Voltar ao inicio</a>
    </body>
</html>
{%endblock%}

connectedin/usuarios/templates/base_usuario.html
{% load staticfiles %} 
<!DOCTYPE html> 
<html lang="pt"> 
<head> <meta charset="utf-8"> 
<meta name="viewport" content="width=device-width"> 
<title>ConnectedIn</title> 
<link href="{% static "styles/bootstrap.css" %}" rel="stylesheet"> 
<link href="{% static "styles/signin.css" %}" rel="stylesheet"> 
</head> 
<body> 
<div class="container">
 {% block body %} {% endblock %} 
 </div> 
 </body>
</html> 

connectedin/usuarios/templates/login.html
{% extends "base_usuario.html" %} 
{% block body %} 
<form class="form-signin" role="form" action="{% url 'login' %}" method="post"> 
{% csrf_token %} 
<h2 class="form-signin-heading">Login</h2> 
<input id="id_username" name="username" class="form-control" placeholder="Nome" required autofocus> 
<input type="password" id="id_password" name="password" class="form-control" placeholder="Senha" required> 
<button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button> 
{% if form.errors %} 
<div class="alert alert-danger">
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button> 
Por favor, verifique o Email e/ou Senha informados 
</div> 
{% endif %} 
<a href="{% url 'registrar' %}">registre-se</a> 
</form>
{% endblock %}

connectedin/usuarios/templates/registrar.html
{% extends "base_usuario.html" %} 
{% block body %} 
<form class="form-signin" action="{% url 'registrar' %}" method="post">
 {% csrf_token %} 
 <h2 class="form-signin-heading">Crie seu usuário</h2> 
    <input id="id_email" name="email" class="form-control" placeholder="Email *" required autofocus> 
    <input id="id_nome" name="nome" class="form-control" placeholder="Nome *" required > 
    <input type="password" id="id_senha" name="senha" class="form-control" placeholder="Senha *" required> 
    <hr /> 
    <input id="id_telefone" name="telefone" class="form-control" placeholder="Telefone" required> 
    <input id="id_nome_empresa" name="nome_empresa" class="form-control" placeholder="Empresa" required> 
    <hr/> 
    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Registrar</button> 
 {% if form.errors %} 
    <div class="alert alert-danger"> 
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button> 
        {{form.non_field_errors}} 
    </div> 
 {% endif %}
 </form> 
 {% endblock %}